"""
Train the behavioural Isolation Forest on the CERT Insider Threat r4.2
dataset (Carnegie Mellon University) so the model learns "normal" from
~1,000 realistic users instead of only the synthetic demo profiles.

CERT is a widely-cited, realistic UEBA benchmark (synthetic background +
seeded malicious insiders, generated by CMU/ExactData under DARPA I2O). It
records logon/logoff, removable-device (USB) use, file access and web
activity per user - which map onto this project's behavioural features.

    Download (free, accept the terms):
      https://kilthub.cmu.edu/articles/dataset/Insider_Threat_Test_Dataset/12841247
    Get release r4.2, unpack, and place these files under
    data/datasets/cert/ :
        logon.csv   device.csv   file.csv   http.csv

Honest limitation: CERT does NOT record process launches or authentication
FAILURES, and carries no IP addresses. So four of the eighteen model
features cannot be filled from CERT and are left at zero
(process_start, distinct_processes, file_to_process_ratio, failed_login);
distinct_ips is proxied by the number of distinct machines the user used,
and removable_file_events is only available on r5/r6 (the to_removable_media
flag) - it stays zero on r4.2. The model therefore learns normal from the
CERT-observable behavioural dimensions (work hours, session length,
off-hours activity and off-hours LOGINS, weekend activity, activity
rate/spread, file volume and file-type variety, login count, USB use,
machine spread). This is stated so the thesis does not overclaim.

Usage:
    python -m scripts.cert_train
"""

import os
import re
import sys
from collections import defaultdict

import numpy as np
import pandas as pd

_EXT_RE = re.compile(r"\.([A-Za-z0-9]{1,6})(?=[\s\"'|,;)\]]|$)")


def _ext(name):
    m = _EXT_RE.findall(str(name))
    return m[-1].lower() if m else None

sys.path.insert(
    0, os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
)

from models.feature_vector import ML_MODEL_FEATURES, CERT_EXTRA_FEATURES
from ml.trainer import BehaviorTrainer

DATA_DIR = os.path.join("data", "datasets", "cert")
FILES = {
    "logon": os.path.join(DATA_DIR, "logon.csv"),
    "device": os.path.join(DATA_DIR, "device.csv"),
    "file": os.path.join(DATA_DIR, "file.csv"),
    "http": os.path.join(DATA_DIR, "http.csv"),
    "email": os.path.join(DATA_DIR, "email.csv"),
}
OUT_DATASET = os.path.join("data", "ml_cert_dataset.csv")
OUT_MODEL = os.path.join("ml", "model_cert.joblib")
OUT_MODEL_EXT = os.path.join("ml", "model_cert_ext.joblib")  # + email/web

CHUNK = 1_000_000
DATE_FMT = "%m/%d/%Y %H:%M:%S"      # CERT timestamp format
WORK_START, WORK_END = 8, 18        # business hours -> off-hours outside

# The CERT synthetic organisation's own e-mail domain; recipients outside
# it count as "external" (a bulk-external-mail day is an exfil signal).
CERT_ORG_DOMAIN = "dtaa.com"

_DOMAIN_RE = re.compile(r"https?://([^/\s]+)", re.IGNORECASE)
_EMAIL_RE = re.compile(r"[\w.\-+]+@([\w.\-]+)")

# Per (user, day) accumulators, kept as light scalars/sets so the whole
# dataset streams through in bounded memory.
tot = defaultdict(int)          # total events (all sources)
off = defaultdict(int)          # events outside business hours
minh = {}                       # earliest activity hour
maxh = {}                       # latest activity hour
logon_cnt = defaultdict(int)    # number of Logon events
first_logon = {}                # earliest Logon hour
last_logoff = {}                # latest Logoff hour
file_cnt = defaultdict(int)     # file-access events
usb_cnt = defaultdict(int)      # USB Connect events
pcs = defaultdict(set)          # distinct machines used
weekend = {}                    # 1 if the day is Sat/Sun
off_logon = defaultdict(int)    # Logon events outside business hours
file_types = defaultdict(set)   # distinct file extensions touched
removable = defaultdict(int)    # files flagged to/from removable media

# E-mail / web accumulators (CERT-only benchmark features).
web_cnt = defaultdict(int)      # http requests
web_domains = defaultdict(set)  # distinct domains browsed
email_sent = defaultdict(int)   # e-mails sent
email_ext = defaultdict(int)    # sent e-mails with an external recipient
email_attach = defaultdict(int)  # attachments sent


def _keys(chunk):
    dt = pd.to_datetime(chunk["date"], format=DATE_FMT, errors="coerce")
    ok = dt.notna()
    dt = dt[ok]
    chunk = chunk[ok]
    hour = dt.dt.hour.to_numpy()
    day = dt.dt.normalize().to_numpy()
    user = chunk["user"].to_numpy()
    pc = (chunk["pc"].to_numpy() if "pc" in chunk.columns
          else np.array([""] * len(chunk)))
    is_off = ((hour < WORK_START) | (hour >= WORK_END)).astype(int)
    is_wknd = (dt.dt.weekday >= 5).astype(int).to_numpy()
    return user, day, hour, pc, is_off, is_wknd, chunk


def _col(chunk, name):
    return (chunk[name].astype(str).to_numpy()
            if name in chunk.columns else None)


def _absorb(chunk, kind):
    """Fold one chunk of one source file into the global accumulators."""
    user, day, hour, pc, is_off, is_wknd, chunk = _keys(chunk)
    activity = _col(chunk, "activity")
    fname = _col(chunk, "filename")
    rem = _col(chunk, "to_removable_media")
    url = _col(chunk, "url")
    to = _col(chunk, "to")
    cc = _col(chunk, "cc")
    bcc = _col(chunk, "bcc")
    attach = _col(chunk, "attachments")

    for i in range(len(user)):
        k = (user[i], day[i])
        h = int(hour[i])
        tot[k] += 1
        off[k] += int(is_off[i])
        if k not in minh or h < minh[k]:
            minh[k] = h
        if k not in maxh or h > maxh[k]:
            maxh[k] = h
        pcs[k].add(pc[i])
        weekend[k] = int(is_wknd[i])

        if kind == "logon" and activity is not None:
            act = activity[i].lower()
            if "logon" in act:
                logon_cnt[k] += 1
                if int(is_off[i]):
                    off_logon[k] += 1
                if k not in first_logon or h < first_logon[k]:
                    first_logon[k] = h
            elif "logoff" in act:
                if k not in last_logoff or h > last_logoff[k]:
                    last_logoff[k] = h
        elif kind == "device" and activity is not None:
            if "connect" in activity[i].lower():
                usb_cnt[k] += 1
        elif kind == "file":
            file_cnt[k] += 1
            if fname is not None:
                ext = _ext(fname[i])
                if ext:
                    file_types[k].add(ext)
            if rem is not None and rem[i].strip().lower() in (
                    "true", "1", "yes"):
                removable[k] += 1
        elif kind == "http":
            web_cnt[k] += 1
            if url is not None:
                m = _DOMAIN_RE.match(url[i]) or _DOMAIN_RE.search(url[i])
                if m:
                    web_domains[k].add(m.group(1).lower())
        elif kind == "email":
            # A sent e-mail (activity "Send"); a View is inbound noise.
            if activity is None or "send" in activity[i].lower():
                email_sent[k] += 1
                recipients = " ".join(
                    r[i] for r in (to, cc, bcc)
                    if r is not None and r[i] and r[i].lower() != "nan"
                )
                domains = {d.lower() for d in _EMAIL_RE.findall(recipients)}
                if any(CERT_ORG_DOMAIN not in d for d in domains):
                    email_ext[k] += 1
                if attach is not None:
                    try:
                        email_attach[k] += int(float(attach[i]))
                    except (ValueError, TypeError):
                        pass


def _stream(path, kind):
    want = {"date", "user", "pc", "activity", "filename",
            "to_removable_media", "url", "to", "cc", "bcc", "attachments"}
    reader = pd.read_csv(
        path, chunksize=CHUNK,
        usecols=lambda c: c.strip().lower() in want,
    )
    rows = 0
    for chunk in reader:
        chunk.columns = [c.strip().lower() for c in chunk.columns]
        _absorb(chunk, kind)
        rows += len(chunk)
        print(f"    {kind}: {rows:,} rows", end="\r")
    print(f"    {kind}: {rows:,} rows        ")


def build_rows():
    rows = []
    for k in tot:
        user, _day = k
        total = tot[k]
        lo = minh.get(k, 0)
        hi = maxh.get(k, 0)
        active = max(1, hi - lo)
        login_h = first_logon.get(k, lo)
        logout_h = last_logoff.get(k, hi)
        rows.append({
            "username": user,
            # --- WHEN ---
            "login_hour": float(login_h),
            "logout_hour": float(logout_h),
            "session_span": float(max(0, logout_h - login_h)),
            "off_hours_ratio": round(off[k] / total, 4) if total else 0.0,
            "weekend_activity": weekend.get(k, 0),
            # --- HOW INTENSE ---
            "event_rate": round(total / active, 4),
            "active_hours": int(hi - lo),
            "process_start": 0,          # not recorded by CERT
            "file_access": file_cnt.get(k, 0),
            # --- STYLE ---
            "distinct_processes": 0,     # not recorded by CERT
            "file_to_process_ratio": 0.0,  # needs process data
            # --- AUTH ---
            "failed_login": 0,           # CERT logs no auth failures
            "login_attempts": logon_cnt.get(k, 0),
            "off_hours_logon": off_logon.get(k, 0),
            # --- FILE STYLE ---
            "distinct_file_types": len(file_types.get(k, ())),
            # --- DEVICE / NETWORK ---
            "usb_events": usb_cnt.get(k, 0),
            "removable_file_events": removable.get(k, 0),  # r5/r6 flag; 0 on r4.2
            "distinct_ips": len(pcs.get(k, ())),   # distinct machines proxy
            # --- E-MAIL / WEB (CERT-only benchmark features) ---
            "web_events": web_cnt.get(k, 0),
            "distinct_web_domains": len(web_domains.get(k, ())),
            "email_sent": email_sent.get(k, 0),
            "external_email_ratio": (
                round(email_ext.get(k, 0) / email_sent[k], 4)
                if email_sent.get(k) else 0.0
            ),
            "email_attachments": email_attach.get(k, 0),
            "label": 0,                  # normal background baseline
        })
    return rows


def main():
    present = {k: p for k, p in FILES.items() if os.path.exists(p)}
    if not present:
        print(
            "CERT files not found in " + DATA_DIR + "/.\n\n"
            "Download the CERT Insider Threat Test Dataset (free) from:\n"
            "  https://kilthub.cmu.edu/articles/dataset/"
            "Insider_Threat_Test_Dataset/12841247\n"
            "Take release r4.2, unpack it, and copy these files into "
            + DATA_DIR + "/ :\n"
            "  logon.csv  device.csv  file.csv  http.csv\n"
            "(logon.csv alone already trains a usable model; the others "
            "add file/USB/web behaviour.)"
        )
        return

    print("Streaming CERT sources ...")
    for kind in ("logon", "device", "file", "http", "email"):
        if kind in present:
            _stream(present[kind], kind)
        else:
            print(f"    {kind}: (missing, skipped)")

    print("Aggregating per user-day sessions ...")
    rows = build_rows()
    df = pd.DataFrame(rows)
    cols = ["username"] + ML_MODEL_FEATURES + CERT_EXTRA_FEATURES + ["label"]
    df = df[cols]

    os.makedirs(os.path.dirname(OUT_DATASET), exist_ok=True)
    df.to_csv(OUT_DATASET, index=False)

    users = df["username"].nunique()
    print(f"\nBuilt {len(df):,} normal sessions from {users} users.")
    print(f"Dataset written to {OUT_DATASET}")

    zero_cols = [c for c in ML_MODEL_FEATURES + CERT_EXTRA_FEATURES
                 if (df[c] == 0).all()]
    if zero_cols:
        print("Note: these features are all-zero (source file not present "
              "or not recorded by CERT): " + ", ".join(zero_cols))

    # Base model: the deployed behavioural feature set (unchanged).
    print("\nTraining Isolation Forest on CERT normal behaviour ...")
    BehaviorTrainer().train(dataset_path=OUT_DATASET, model_path=OUT_MODEL)

    # Extended model: the same features PLUS e-mail/web (benchmark-only).
    # Trained whenever the CERT e-mail/web sources actually contributed,
    # so the thesis can measure what those planes add (future-work item).
    email_web_present = any(
        not (df[c] == 0).all() for c in CERT_EXTRA_FEATURES
    )
    if email_web_present:
        print("\nTraining EXTENDED model (+ e-mail/web features) ...")
        ext = BehaviorTrainer()
        ext.FEATURES = ML_MODEL_FEATURES + CERT_EXTRA_FEATURES
        ext.train(dataset_path=OUT_DATASET, model_path=OUT_MODEL_EXT)
        print(f"Extended model saved to {OUT_MODEL_EXT}. Run "
              "`python -m scripts.cert_eval` to measure the ROC-AUC delta.")
    else:
        print("\n(E-mail/web sources absent — extended model skipped. "
              "Add email.csv / http.csv to " + DATA_DIR + "/ to enable it.)")

    print(
        "\nDone. To use the base model for the reproducible `analyze` demo, "
        "replace ml/model.joblib with " + OUT_MODEL + " (keep a backup), "
        "or point the pipeline's SAMPLE_MODEL at it."
    )


if __name__ == "__main__":
    main()
