"""
Train the behavioural Isolation Forest on the CERT Insider Threat r4.2
dataset (Carnegie Mellon University) so the model learns "normal" from
~1,000 realistic users instead of only the synthetic demo profiles.

CERT is a widely-cited, realistic UEBA benchmark (synthetic background +
seeded malicious insiders, generated by CMU/ExactData under DARPA I2O). It
records logon/logoff, removable-device (USB) use, file access and web
activity per user - which map onto this project's behavioural features.

    Download (free, accept the terms):
      https://kilthub.cmu.edu/articles/dataset/Insider_Threat_Test_Dataset/12841247
    Get release r4.2, unpack, and place these files under
    data/datasets/cert/ :
        logon.csv   device.csv   file.csv   http.csv

Honest limitation: CERT does NOT record process launches or authentication
FAILURES, and carries no IP addresses. So four of the eighteen model
features cannot be filled from CERT and are left at zero
(process_start, distinct_processes, file_to_process_ratio, failed_login);
distinct_ips is proxied by the number of distinct machines the user used,
and removable_file_events is only available on r5/r6 (the to_removable_media
flag) - it stays zero on r4.2. The model therefore learns normal from the
CERT-observable behavioural dimensions (work hours, session length,
off-hours activity and off-hours LOGINS, weekend activity, activity
rate/spread, file volume and file-type variety, login count, USB use,
machine spread). This is stated so the thesis does not overclaim.

Usage:
    python -m scripts.cert_train
"""

import os
import re
import sys
from collections import defaultdict

import numpy as np
import pandas as pd

_EXT_RE = re.compile(r"\.([A-Za-z0-9]{1,6})(?=[\s\"'|,;)\]]|$)")


def _ext(name):
    m = _EXT_RE.findall(str(name))
    return m[-1].lower() if m else None

sys.path.insert(
    0, os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
)

from models.feature_vector import ML_MODEL_FEATURES
from ml.trainer import BehaviorTrainer

DATA_DIR = os.path.join("data", "datasets", "cert")
FILES = {
    "logon": os.path.join(DATA_DIR, "logon.csv"),
    "device": os.path.join(DATA_DIR, "device.csv"),
    "file": os.path.join(DATA_DIR, "file.csv"),
    "http": os.path.join(DATA_DIR, "http.csv"),
}
OUT_DATASET = os.path.join("data", "ml_cert_dataset.csv")
OUT_MODEL = os.path.join("ml", "model_cert.joblib")

CHUNK = 1_000_000
DATE_FMT = "%m/%d/%Y %H:%M:%S"      # CERT timestamp format
WORK_START, WORK_END = 8, 18        # business hours -> off-hours outside

# Per (user, day) accumulators, kept as light scalars/sets so the whole
# dataset streams through in bounded memory.
tot = defaultdict(int)          # total events (all sources)
off = defaultdict(int)          # events outside business hours
minh = {}                       # earliest activity hour
maxh = {}                       # latest activity hour
logon_cnt = defaultdict(int)    # number of Logon events
first_logon = {}                # earliest Logon hour
last_logoff = {}                # latest Logoff hour
file_cnt = defaultdict(int)     # file-access events
usb_cnt = defaultdict(int)      # USB Connect events
pcs = defaultdict(set)          # distinct machines used
weekend = {}                    # 1 if the day is Sat/Sun
off_logon = defaultdict(int)    # Logon events outside business hours
file_types = defaultdict(set)   # distinct file extensions touched
removable = defaultdict(int)    # files flagged to/from removable media


def _keys(chunk):
    dt = pd.to_datetime(chunk["date"], format=DATE_FMT, errors="coerce")
    ok = dt.notna()
    dt = dt[ok]
    chunk = chunk[ok]
    hour = dt.dt.hour.to_numpy()
    day = dt.dt.normalize().to_numpy()
    user = chunk["user"].to_numpy()
    pc = (chunk["pc"].to_numpy() if "pc" in chunk.columns
          else np.array([""] * len(chunk)))
    is_off = ((hour < WORK_START) | (hour >= WORK_END)).astype(int)
    is_wknd = (dt.dt.weekday >= 5).astype(int).to_numpy()
    return user, day, hour, pc, is_off, is_wknd, chunk


def _absorb(chunk, kind):
    """Fold one chunk of one source file into the global accumulators."""
    user, day, hour, pc, is_off, is_wknd, chunk = _keys(chunk)
    activity = (chunk["activity"].astype(str).to_numpy()
                if "activity" in chunk.columns else None)
    fname = (chunk["filename"].astype(str).to_numpy()
             if "filename" in chunk.columns else None)
    rem = (chunk["to_removable_media"].astype(str).to_numpy()
           if "to_removable_media" in chunk.columns else None)

    for i in range(len(user)):
        k = (user[i], day[i])
        h = int(hour[i])
        tot[k] += 1
        off[k] += int(is_off[i])
        if k not in minh or h < minh[k]:
            minh[k] = h
        if k not in maxh or h > maxh[k]:
            maxh[k] = h
        pcs[k].add(pc[i])
        weekend[k] = int(is_wknd[i])

        if kind == "logon" and activity is not None:
            act = activity[i].lower()
            if "logon" in act:
                logon_cnt[k] += 1
                if int(is_off[i]):
                    off_logon[k] += 1
                if k not in first_logon or h < first_logon[k]:
                    first_logon[k] = h
            elif "logoff" in act:
                if k not in last_logoff or h > last_logoff[k]:
                    last_logoff[k] = h
        elif kind == "device" and activity is not None:
            if "connect" in activity[i].lower():
                usb_cnt[k] += 1
        elif kind == "file":
            file_cnt[k] += 1
            if fname is not None:
                ext = _ext(fname[i])
                if ext:
                    file_types[k].add(ext)
            if rem is not None and rem[i].strip().lower() in (
                    "true", "1", "yes"):
                removable[k] += 1


def _stream(path, kind):
    want = {"date", "user", "pc", "activity", "filename",
            "to_removable_media"}
    reader = pd.read_csv(
        path, chunksize=CHUNK,
        usecols=lambda c: c.strip().lower() in want,
    )
    rows = 0
    for chunk in reader:
        chunk.columns = [c.strip().lower() for c in chunk.columns]
        _absorb(chunk, kind)
        rows += len(chunk)
        print(f"    {kind}: {rows:,} rows", end="\r")
    print(f"    {kind}: {rows:,} rows        ")


def build_rows():
    rows = []
    for k in tot:
        user, _day = k
        total = tot[k]
        lo = minh.get(k, 0)
        hi = maxh.get(k, 0)
        active = max(1, hi - lo)
        login_h = first_logon.get(k, lo)
        logout_h = last_logoff.get(k, hi)
        rows.append({
            "username": user,
            # --- WHEN ---
            "login_hour": float(login_h),
            "logout_hour": float(logout_h),
            "session_span": float(max(0, logout_h - login_h)),
            "off_hours_ratio": round(off[k] / total, 4) if total else 0.0,
            "weekend_activity": weekend.get(k, 0),
            # --- HOW INTENSE ---
            "event_rate": round(total / active, 4),
            "active_hours": int(hi - lo),
            "process_start": 0,          # not recorded by CERT
            "file_access": file_cnt.get(k, 0),
            # --- STYLE ---
            "distinct_processes": 0,     # not recorded by CERT
            "file_to_process_ratio": 0.0,  # needs process data
            # --- AUTH ---
            "failed_login": 0,           # CERT logs no auth failures
            "login_attempts": logon_cnt.get(k, 0),
            "off_hours_logon": off_logon.get(k, 0),
            # --- FILE STYLE ---
            "distinct_file_types": len(file_types.get(k, ())),
            # --- DEVICE / NETWORK ---
            "usb_events": usb_cnt.get(k, 0),
            "removable_file_events": removable.get(k, 0),  # r5/r6 flag; 0 on r4.2
            "distinct_ips": len(pcs.get(k, ())),   # distinct machines proxy
            "label": 0,                  # normal background baseline
        })
    return rows


def main():
    present = {k: p for k, p in FILES.items() if os.path.exists(p)}
    if not present:
        print(
            "CERT files not found in " + DATA_DIR + "/.\n\n"
            "Download the CERT Insider Threat Test Dataset (free) from:\n"
            "  https://kilthub.cmu.edu/articles/dataset/"
            "Insider_Threat_Test_Dataset/12841247\n"
            "Take release r4.2, unpack it, and copy these files into "
            + DATA_DIR + "/ :\n"
            "  logon.csv  device.csv  file.csv  http.csv\n"
            "(logon.csv alone already trains a usable model; the others "
            "add file/USB/web behaviour.)"
        )
        return

    print("Streaming CERT sources ...")
    for kind in ("logon", "device", "file", "http"):
        if kind in present:
            _stream(present[kind], kind)
        else:
            print(f"    {kind}: (missing, skipped)")

    print("Aggregating per user-day sessions ...")
    rows = build_rows()
    df = pd.DataFrame(rows)
    cols = ["username"] + ML_MODEL_FEATURES + ["label"]
    df = df[cols]

    os.makedirs(os.path.dirname(OUT_DATASET), exist_ok=True)
    df.to_csv(OUT_DATASET, index=False)

    users = df["username"].nunique()
    print(f"\nBuilt {len(df):,} normal sessions from {users} users.")
    print(f"Dataset written to {OUT_DATASET}")

    zero_cols = [c for c in ML_MODEL_FEATURES
                 if (df[c] == 0).all()]
    if zero_cols:
        print("Note: these features are all-zero (not recorded by CERT): "
              + ", ".join(zero_cols))

    print("\nTraining Isolation Forest on CERT normal behaviour ...")
    BehaviorTrainer().train(dataset_path=OUT_DATASET, model_path=OUT_MODEL)
    print(
        "\nDone. To use this model for the reproducible `analyze` demo, "
        "replace ml/model.joblib with " + OUT_MODEL + " (keep a backup), "
        "or point the pipeline's SAMPLE_MODEL at it."
    )


if __name__ == "__main__":
    main()
